backend:
  name: git-gateway
  branch: main   # or master if your repo uses that

media_folder: "uploads"      # where uploaded images are stored in repo
public_folder: "/uploads"    # how site references images

collections:
  - name: "content"
    label: "Site Content"
    files:
      - file: "content.md"
        label: "Main Content"
        name: "main"
        fields:
          - label: "Hero"
            name: "hero"
            widget: "markdown"
            hint: "Edit hero title & subhead (# Hero section)"

          - label: "About"
            name: "about"
            widget: "markdown"
            hint: "Edit About section (title, paragraphs)"

          - label: "Services"
            name: "services"
            widget: "markdown"
            hint: "Edit services title, subhead & items"

          - label: "Pricing"
            name: "pricing"
            widget: "markdown"
            hint: "Edit pricing subhead & service lists"

          - label: "Gallery"
            name: "gallery"
            widget: "markdown"
            hint: "Edit gallery title & subhead"

          - label: "Testimonials"
            name: "testimonials"
            widget: "markdown"
            hint: "Edit testimonials list"

          - label: "Booking"
            name: "booking"
            widget: "markdown"
            hint: "Edit booking title & subhead"

          - label: "Contact"
            name: "contact"
            widget: "markdown"
            hint: "Edit contact details & socials"

          - label: "FAQ"
            name: "faq"
            widget: "markdown"
            hint: "Edit FAQ questions & answers"
