backend:
  name: github
  repo: Kunalji1012/salon   # replace with your GitHub user/repo
  branch: main

media_folder: "images/uploads"     # where uploaded files are stored in repo
public_folder: "/images/uploads"   # path for the website to access them

collections:
  - name: "site"
    label: "Salon Website"
    files:
      - file: "content.md"
        label: "Website Content"
        name: "content"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subhead", name: "hero_subhead", widget: "text" }
          - { label: "About", name: "about", widget: "markdown" }
          - { label: "Services", name: "services", widget: "markdown" }
          - { label: "Pricing", name: "pricing", widget: "markdown" }
          - { label: "Testimonials", name: "testimonials", widget: "markdown" }
          - { label: "Gallery", name: "gallery", widget: "markdown" }
          - { label: "Booking", name: "booking", widget: "markdown" }
          - { label: "Contact", name: "contact", widget: "markdown" }
          - { label: "FAQ", name: "faq", widget: "markdown" }
